baseURL = "/"
languageCode = "en-us"
theme = "simple-intro"
title = "Title"
publishDir = "docs"

[params]
    mainbg = "https://cdn.discordapp.com/attachments/704599857083449366/722677588484423721/luca-bravo-XJXWbfSo2f0-unsplash_1.jpg"
    name = "Gangjun Lee"
    mainTitle = "Gangjun Lee"
    mainText = "Full-stack Developer"

[menus]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "#about"
    [[menu.main]]
        identifier = "skills"
        name = "Skills"
        url = "#skills"
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "#projects"

    